[pytest]
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
pythonpath = .

addopts = -ra --tb=native --import-mode=append
testpaths = .
norecursedirs = .git .venv
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::ResourceWarning