[pytest]
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
addopts = -ra --tb=native
testpaths = .
norecursedirs = .git .venv
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::ResourceWarning